# Generated by Django 4.2.4 on 2023-08-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='record_label',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='released',
            field=models.DateField(null=True),
        ),
    ]
