# Generated by Django 4.2.4 on 2023-08-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_record_record_label_record_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
