# Generated by Django 4.2.4 on 2023-08-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_record_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='slug',
        ),
    ]
